apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seven-stone
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seven-stone
  template:
    metadata:
      labels:
        app: seven-stone
    spec:
      containers:
        - name: react-container
          image: 401544946555.dkr.ecr.ap-south-1.amazonaws.com/seven-stone:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: load-dep-001
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: seven-stone
  ports:
    - name: http
      protocol: TCP
      port: 80
