name: Deploy React App to AWS EKS

on:
  push:
    branches:
      - main
      - uat
      - test
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Check if ECR Repository Exists
        id: check-ecr
        continue-on-error: true
        run: |
          aws ecr describe-repositories --repository-names react-app-test --region ap-south-1

      - name: Create ECR Repository if not exists
        if: steps.check-ecr.outcome == 'failure'
        run: |
          aws ecr create-repository --repository-name react-app-test --region ap-south-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 401544946555.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t seven-stone .

      - name: Tag Docker Image
        run: |
          docker tag react-app-test:latest 401544946555.dkr.ecr.ap-south-1.amazonaws.com/seven-stone:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 401544946555.dkr.ecr.ap-south-1.amazonaws.com/seven-stone:latest

      - name: Update Kubernetes Deployment
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name your-cluster-name
          kubectl set image deployment/react-app react-container=401544946555.dkr.ecr.ap-south-1.amazonaws.com/seven-stone:latest
          kubectl rollout status deployment/react-app

