name: Deploy React App to AWS EKS

on:
  push:
    branches:
      - main
      - uat
      - test
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # Use OIDC instead of Access Key
          role-session-name: GitHubActionsSession

      # Check if ECR Repository Exists
      - name: Check if ECR Repository Exists
        id: check-ecr
        continue-on-error: true
        run: |
          if ! aws ecr describe-repositories --repository-names seven-stone --region ap-south-1 > /dev/null 2>&1; then
            echo "ECR_NOT_FOUND=true" >> $GITHUB_ENV
          fi

      # Create ECR Repository if not exists
      - name: Create ECR Repository
        if: env.ECR_NOT_FOUND == 'true'
        run: |
          aws ecr create-repository --repository-name seven-stone --region ap-south-1

      # Login to AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 401544946555.dkr.ecr.ap-south-1.amazonaws.com

      # Build & Push Docker Image
      - name: Build, Tag & Push Docker Image
        run: |
          docker build -t seven-stone:latest .
          docker tag seven-stone:latest 401544946555.dkr.ecr.ap-south-1.amazonaws.com/seven-stone:latest
          docker push 401544946555.dkr.ecr.ap-south-1.amazonaws.com/seven-stone:latest

      # Update Kubernetes Deployment
      - name: Update Kubernetes Deployment
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name AWS-EKS

          # Check Kubernetes Cluster
          kubectl cluster-info
          kubectl get nodes
          kubectl get namespaces

          # Deploy or Update React App
          if ! kubectl get deployment seven-stone -n default &>/dev/null; then
            echo "Deployment not found, creating..."
            kubectl apply -f k8s/deployment.yaml
          else
            echo "Updating deployment..."
            kubectl set image deployment/seven-stone react-container=401544946555.dkr.ecr.ap-south-1.amazonaws.com/seven-stone:latest
            kubectl rollout status deployment/seven-stone
          fi

